stages:
  - build
  - test

build the card:
  stage: build
  script:
    - mkdir build
    - cd build
    - touch car.txt
    - echo "chassis" > car.txt
    - echo "engine" >> car.txt
    - echo "wheels" >> car.txt
  artifacts:
    paths:
      - build/

test the car:
  stage: test
  script:
    - test -f build/car.txt
    - grep "chassis" build/car.txt
    - grep "engine" build/car.txt
    - grep "wheels" build/car.txt